<a href="https://colab.research.google.com/github/Siddhi-Salunkhe/ML/blob/main/Practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")


Using NumPy


In [ ]:
import numpy as np

**Numpy Arrays**
NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

**Creating NumPy Arrays**

In [ ]:
my_list = [1,2,3]
my_list


[1, 2, 3]

In [ ]:

np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


**Built-in Methods**
   **arange**
   
Return evenly spaced values within a given interval.

In [ ]:

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**zeros and ones**


Generate arrays of zeros or ones

In [ ]:

np.zeros(3)

array([0., 0., 0.])

In [ ]:

np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:

np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])


**linspace**



Return evenly spaced numbers over a specified interval.

In [ ]:

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])


**eye**

Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


**Random**

Numpy also has lots of ways to create random number arrays:

In [ ]:
np.random.rand(5,5)

array([[0.1438258 , 0.97655117, 0.12470403, 0.88325103, 0.65830935],
       [0.60979742, 0.08018771, 0.40857131, 0.11500105, 0.14814233],
       [0.33991186, 0.23006638, 0.06985187, 0.08054111, 0.9895964 ],
       [0.55474918, 0.09291061, 0.63188249, 0.90223838, 0.83215161],
       [0.43237407, 0.74010217, 0.74279206, 0.15537244, 0.04832061]])

In [ ]:
np.random.rand(2)

array([0.46112667, 0.8965306 ])


**randn**

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

array([ 0.28972669, -0.94570375])

In [ ]:
np.random.randn(5,5)

array([[-0.34676057,  0.13882893,  0.69153428,  1.60659807, -0.01221582],
       [ 0.37382934,  0.67856204, -2.69901714,  0.53620139, -0.24529696],
       [ 0.31011269, -0.81636377, -0.38162117, -1.6233847 , -1.6797303 ],
       [ 0.44738376, -0.86615408, -1.23518956,  0.569427  ,  0.36817664],
       [-0.11625962, -1.01318356,  0.07888922,  1.22983253,  1.45833079]])

**randint**


Return random integers from low (inclusive) to high (exclusive).

In [ ]:

np.random.randint(1,100)

86

In [ ]:
np.random.randint(0,50,10)

array([33, 29,  5, 24,  4, 38, 35,  0, 37, 37])


**Array Attributes and Methods**

In [ ]:

arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([16, 26, 35,  8, 32, 17, 22, 21, 14, 12])


**Reshape**

Returns an array containing the same data with a new shape.

In [ ]:

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


**max,min,argmax,argmin**

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:

ranarr

array([16, 26, 35,  8, 32, 17, 22, 21, 14, 12])

In [ ]:
ranarr.max()

np.int64(35)

In [ ]:
ranarr.min()

np.int64(8)

In [ ]:

ranarr.argmax()

np.int64(2)

In [ ]:

ranarr.argmin()

np.int64(3)

## Shape

Shape is an attribute that arrays have (not a method):

vector


In [ ]:
arr.shape


(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

**dtype**
You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')